/* global React, SectionHeader, CTAForm, Logo */

// ===== FAQ + Footer (with repeat CTA) =====
const FAQ = ({ theme, accent, density }) => {
  const pad = density === "tight" ? "60px 0" : "100px 0";
  const items = [
    {
      q: "Is the air-gapped tier actually viable for serious litigation?",
      a: "Yes. Llama 3.3 70B and Qwen 2.5 72B running on a single H100 node match GPT-4-class performance on legal benchmarks for our workloads. We ship optimized fine-tunes for contract review, deposition prep, and discovery. Most mid-size firms run on 2× H100 nodes — total hardware cost amortizes against one Harvey AI seat-year.",
    },
    {
      q: "How does the citation verifier achieve 2.1% hallucination?",
      a: "Every citation generated by any agent is gated through a deterministic verifier before it reaches a draft. The verifier resolves the cite against Westlaw/KeyCite/Shepard's, confirms the proposition matches the cited holding, and flags negative treatment. Cites that fail are removed, never silently retained. Our eval set and methodology are public at deaglelabs.com/eval.",
    },
    {
      q: "Does using AI on client matters violate my ethical duties?",
      a: "Using AI does not, but using cloud AI on privileged material likely does — model providers train on inputs absent contractual carve-outs. Deagle's BYOC and air-gapped tiers eliminate the issue entirely: client data never leaves your control plane. We provide the model engagement letter language used by 200+ firms.",
    },
    {
      q: "What does it cost?",
      a: "Cloud SaaS starts at $89/seat/month (1–10 seats). BYOC is per-firm licensing from $4,800/month. Air-gapped is $24,000/year flat — unlimited seats, your hardware. No PSO requirements. No multi-year minimums.",
    },
    {
      q: "How is implementation handled?",
      a: "Cloud: 5 minutes from signup to first matter. BYOC: 1–2 days with your DevOps team using our Helm chart. Air-gapped: typically 3–5 days including hardware setup. We don't sell professional services — if it can't be self-serve in a week, we consider it a product failure.",
    },
    {
      q: "What about Bates numbering, EDRM imports, and other tablestakes?",
      a: "Built in, not bolted on. Native EDRM v2.0 ingestion preserves families and metadata. Bates numbering is generated continuously across productions. Privilege logs update as you review. Concordance and Relativity load files import directly.",
    },
  ];

  return (
    <section style={{ padding: pad, borderTop: `1px solid ${theme.border}` }}>
      <SectionHeader
        theme={theme} accent={accent}
        kicker="§ 06 · Frequently asked"
        title={<>The questions <em style={{ color: accent }}>partners</em> ask first.</>}
      />
      <div style={{ borderTop: `1px solid ${theme.border}` }}>
        {items.map((item, i) => (
          <FAQItem key={i} item={item} idx={i} theme={theme} accent={accent} />
        ))}
      </div>
    </section>
  );
};

const FAQItem = ({ item, idx, theme, accent }) => {
  const [open, setOpen] = React.useState(idx === 0);
  return (
    <div style={{ borderBottom: `1px solid ${theme.border}` }}>
      <button
        onClick={() => setOpen(!open)}
        style={{
          width: "100%",
          background: "none",
          border: "none",
          padding: "28px 0",
          textAlign: "left",
          cursor: "pointer",
          display: "grid",
          gridTemplateColumns: "60px 1fr 40px",
          alignItems: "baseline",
          gap: 24,
          color: theme.fg,
        }}
      >
        <span style={{
          fontFamily: "'JetBrains Mono', monospace",
          fontSize: 11,
          color: theme.muted,
          letterSpacing: "0.06em",
        }}>
          Q.{String(idx + 1).padStart(2, "0")}
        </span>
        <span style={{
          fontFamily: "'Instrument Serif', serif",
          fontSize: 26,
          lineHeight: 1.2,
          letterSpacing: "-0.015em",
        }}>
          {item.q}
        </span>
        <span style={{
          fontFamily: "'JetBrains Mono', monospace",
          fontSize: 18,
          color: open ? accent : theme.muted,
          textAlign: "right",
          transition: "transform 0.2s",
          transform: open ? "rotate(45deg)" : "rotate(0)",
        }}>
          +
        </span>
      </button>
      {open && (
        <div style={{
          display: "grid",
          gridTemplateColumns: "60px 1fr 40px",
          gap: 24,
          paddingBottom: 32,
          animation: "fadein 0.3s ease-out",
        }}>
          <div />
          <div style={{
            fontSize: 16,
            lineHeight: 1.6,
            color: theme.fg2,
            maxWidth: 720,
          }}>
            {item.a}
          </div>
        </div>
      )}
    </div>
  );
};

// ===== Repeat CTA + Footer =====
const FooterCTA = ({ theme, accent, ctaCopy, density }) => {
  const pad = density === "tight" ? "80px 0 60px" : "120px 0 80px";
  return (
    <section style={{
      padding: pad,
      borderTop: `1px solid ${theme.border}`,
      background: theme.surfaceAlt,
      position: "relative",
    }}>
      <div style={{
        display: "grid",
        gridTemplateColumns: "1.1fr 0.9fr",
        gap: 80,
        alignItems: "center",
      }}>
        <div>
          <div style={{
            fontFamily: "'JetBrains Mono', monospace",
            fontSize: 11,
            letterSpacing: "0.12em",
            textTransform: "uppercase",
            color: accent,
            marginBottom: 28,
          }}>
            § 07 · Try it
          </div>
          <h2 style={{
            fontFamily: "'Instrument Serif', serif",
            fontSize: "clamp(48px, 5.4vw, 84px)",
            lineHeight: 0.95,
            letterSpacing: "-0.025em",
            margin: "0 0 24px",
            fontWeight: 400,
            color: theme.fg,
            textWrap: "balance",
          }}>
            See the demo.<br />
            <em style={{ color: accent }}>Bring a real matter.</em>
          </h2>
          <p style={{
            fontSize: 18,
            lineHeight: 1.5,
            maxWidth: 480,
            color: theme.fg2,
            margin: 0,
          }}>
            Hosted demo at <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 15, color: theme.fg }}>demo.deaglelabs.com</span>. No sales call. Drop in a sample brief and run citation verification, privilege detection, and multi-agent review on real work.
          </p>
        </div>
        <div>
          <CTAForm ctaCopy={ctaCopy} theme={theme} accent={accent} />
        </div>
      </div>
    </section>
  );
};

const Footer = ({ theme, accent, logoVariant }) => (
  <footer style={{
    borderTop: `1px solid ${theme.border}`,
    padding: "48px 0 36px",
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 11,
    letterSpacing: "0.04em",
    color: theme.muted,
  }}>
    <div style={{
      display: "grid",
      gridTemplateColumns: "1.5fr 1fr 1fr 1fr",
      gap: 48,
      marginBottom: 48,
    }}>
      <div>
        <Logo variant={logoVariant} size={24} color={theme.fg} />
        <div style={{ marginTop: 16, color: theme.fg2, fontSize: 12, lineHeight: 1.6, fontFamily: "'Inter Tight', sans-serif", letterSpacing: "-0.005em", maxWidth: 280 }}>
          Privileged AI infrastructure for law firms of every size.
        </div>
      </div>
      <FooterCol title="Platform" items={["Document review", "Legal research", "Citation verifier", "Multi-agent", "Discovery"]} theme={theme} />
      <FooterCol title="Deploy" items={["Cloud SaaS", "BYOC / Helm", "Air-gapped", "Pricing", "Security"]} theme={theme} />
      <FooterCol title="Company" items={["Eval methodology", "Documentation", "Trust center", "Contact", "Careers"]} theme={theme} />
    </div>
    <div style={{
      borderTop: `1px solid ${theme.border}`,
      paddingTop: 24,
      display: "flex",
      justifyContent: "space-between",
      flexWrap: "wrap",
      gap: 16,
    }}>
      <span>© 2026 Deagle Labs, Inc. · Made for lawyers, not for legaltech analysts.</span>
      <span>SOC 2 Type II · ISO 27001 · HIPAA · GDPR</span>
    </div>
  </footer>
);

const FooterCol = ({ title, items, theme }) => (
  <div>
    <div style={{
      fontSize: 10,
      letterSpacing: "0.12em",
      textTransform: "uppercase",
      color: theme.fg,
      marginBottom: 16,
      fontWeight: 600,
    }}>
      {title}
    </div>
    <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 8 }}>
      {items.map((i) => (
        <li key={i}>
          <a href="#" style={{ color: theme.fg2, textDecoration: "none" }}>{i}</a>
        </li>
      ))}
    </ul>
  </div>
);

window.FAQ = FAQ;
window.FooterCTA = FooterCTA;
window.Footer = Footer;
